stages:
  - test
  - build
  - run
  - publish

tests:
  stage: test
  image: rust
  script:
    - cargo test

build:amd64:
  stage: build
  image: rust
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/rust-gitlab-example

run:
  stage: run
  image: rust
  script:
    - cargo run

rustdoc:
  stage: build
  image: rust
  script:
    - cargo doc
  artifacts:
    paths:
      - target/doc

pages:
  stage: publish
  image: alpine
  dependencies:
    - build:amd64
    - rustdoc
  script:
    - mkdir -p public
    - mv target/doc public/doc
    - mv target/release/rust-gitlab-example public/rust-gitlab-example-amd64
  artifacts:
    paths:
      - public
  only:
    - master


